// <auto-generated />
namespace IAAITaiwanPractice240823.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddCommentReplytables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCommentReplytables));
        
        string IMigrationMetadata.Id
        {
            get { return "202409130813258_Add Comment & Reply tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
